@baseUrl = http://localhost:3333
# Cole o token recebido no Login aqui para testar as rotas protegidas
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxODZhMWUyZi05MGVlLTQwY2YtYTFkNS0wMDY3ZThlNTMxMjIiLCJyb2xlIjoiQmVuZWZpY2nDoXJpbyIsImlhdCI6MTc3NDgzODkzOH0.NZZxfL70ikZg_0_An9uoSOH_Jwn_GNpvjpbsW6MtbX8

### ===================================================================
### 1. [SUCESSO 200] Health Check
### Expectativa: Retornar status "ok" confirmando que a API está online
### ===================================================================
GET {{baseUrl}}/health


### ===================================================================
### 2. [SUCESSO 201] Registrar Novo Usuário
### Expectativa: Criar conta e retornar mensagem de sucesso com ID
### ===================================================================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "fullName": "larissa",
  "email": "larissa@exemplo.com",
  "password": "senha123",
  "role": "Beneficiário"
}


### ===================================================================
### 3. [SUCESSO 200] Login de Usuário
### Expectativa: Retornar o Token JWT para ser usado nas outras requisições
### ===================================================================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "larissa@exemplo.com",
  "password": "senha123"
}


### ===================================================================
### 4. [ERRO 400/409] Falha no Registro - E-mail já em uso
### Expectativa: Erro credencias inválidas
### ===================================================================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "fullName": "Maria Silva",
  "email": "maria@exemplo.com",
  "password": "senha456",
  "role": "Beneficiário"
}


### ===================================================================
### 5. [ERRO 401] Falha no Login - Credenciais Inválidas
### Expectativa: Erro informando que a senha ou e-mail estão incorretos
### ===================================================================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "maria@exemplo.com",
  "password": "senha_errada_aqui"
}


### ===================================================================
### 6. [SUCESSO 200] Obter Perfil do Usuário Logado (Rota Protegida)
### Expectativa: Retornar os dados do usuário (sem a senha)
### ===================================================================
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{userToken}}


### ===================================================================
### 7. [SUCESSO 200] Atualizar Perfil do Usuário (Rota Protegida)
### Expectativa: Atualizar nome/email e retornar sucesso
### ===================================================================
PUT {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "fullName": "João Silva dos Santos",
  "email": "joao.santos12@exemplo.com"
}


### ===================================================================
### 8. [SUCESSO 200] Atualizar FCM Token (Push Notifications)
### Expectativa: Salvar o token do celular para o Firebase Cloud Messaging
### ===================================================================
PATCH {{baseUrl}}/users/fcm-token
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "fcmToken": "token_simulado_do_firebase_12345"
}


### ===================================================================
### 9. [SUCESSO 200] Excluir Conta - Soft Delete (Rota Protegida)
### Expectativa: Desativar a conta do usuário confirmando a senha
### ===================================================================
DELETE {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "password": "senha123"
}


### ===================================================================
### 10. [SUCESSO 200] Buscar Usuários com Filtros (Apenas Admin)
### Expectativa: Retornar lista paginada de usuários conforme filtros
### ===================================================================
GET {{baseUrl}}/admin/users?page=1&limit=5&search=João&role=Doador
Content-Type: application/json
Authorization: Bearer {{userToken}}

### ===================================================================
### 11. [SUCESSO 200] Buscar perfil publico de Usuários 
### Expectativa: Retornar Perfil Público de Outro Usuário
### ===================================================================

GET {{baseUrl}}/users/d8b8d67f-b5e9-4075-aa98-d680add33736
Authorization: Bearer {{userToken}}

