### Variáveis (Preencha com o token do Login)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NWE5MTYyOS0zMzRmLTRjYmItYWExZi0xMjk5YmI2YTFkYzciLCJyb2xlIjoiQmVuZWZpY2nDoXJpbyIsImlhdCI6MTc3NDgxOTk4OX0.dL7uOyikShDtqph3gsp_F0zyOsuxojfykwHLmfnTeyw
@baseUrl = http://127.0.0.1:3333

### Enviar Documentos para Análise (Upload Real Multipart)
POST {{baseUrl}}/verifications
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="cpf"

12345678909
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="identityDocument"; filename="rg_teste.jpg"
Content-Type: image/jpeg

< ./rg_teste.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="incomeProof"; filename="holerite_teste.jpg"
Content-Type: image/jpeg

< ./holerite_teste.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 2. Consultar Status da Verificação (Visão do Frontend)
GET {{baseUrl}}/verifications/me
Authorization: Bearer {{token}}