@baseUrl = http://localhost:3333
# 1. Cole o token recebido no Login aqui para testar as rotas protegidas
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTNjOTFhMC02YzA0LTQzNTEtYmI3YS1iNjgxNTlmMDhhOGUiLCJyb2xlIjoiQmVuZWZpY2nDoXJpbyIsImlhdCI6MTc3NDg0Mzc2Nn0.GvC0RpJ6qJomQbFRlKoZwZNV6QS-x5J_u70rg4DAbYQ
# 2. Após criar um item, copie o ID dele e cole aqui para testar as rotas de baixo
@itemId = 39e5bc94-42f9-429f-a641-69bd1089270b


#### ===================================================================
### 1. [SUCESSO 201] Criar um Item para Doação (1 Imagem)
### Expectativa: Backend converte Latitude/Longitude pura em geometry Point para injetar no PostGIS
### ===================================================================
POST {{baseUrl}}/items
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "title": "geladeira",
  "description": "Precisa de frete grande para retirar.",
  "category": "Móveis",
  "imageUrls": ["https://exemplo.com/sofa.jpg"],
  "latitude": -23.501533,
  "longitude": -47.458112
}


### ===================================================================
### 3. [SUCESSO 200] Listar Itens (Feed Geográfico e Paginado)
### Expectativa: Dispara ST_DistanceSphere pelo PostGIS, paginando de 10 em 10 itens dentro de 5km
### ===================================================================
GET {{baseUrl}}/items?page=1&limit=10&lat=-23.501533&lng=-47.458112&radius=5000
Content-Type: application/json
Authorization: Bearer {{userToken}}


### ===================================================================
### 4. [SUCESSO 200] Feed Geral SÓ COM PADRÕES DA PAGINAÇÃO
### Expectativa: Rota deve funcionar perfeitamente sem enviar GPS, trazendo os 10 itens globais mais recentes
### ===================================================================
GET {{baseUrl}}/items?page=1
Content-Type: application/json
Authorization: Bearer {{userToken}}



### ===================================================================
### 5. [SUCESSO 200] Listar Itens com Filtro de Categoria
### Expectativa: Retornar apenas itens pertencentes à categoria "Móveis"
### ===================================================================
GET {{baseUrl}}/items?category=Móveis
Content-Type: application/json
Authorization: Bearer {{userToken}}


### ===================================================================
### 6. [SUCESSO 200] Listar Itens por Localização (Raio de Busca)
### Expectativa: Retornar itens mais próximos da coordenada informada
### ===================================================================
GET {{baseUrl}}/items?lat=-23.501533&lng=-47.458112
Content-Type: application/json
Authorization: Bearer {{userToken}}


### ===================================================================
### 7. [SUCESSO 200] Ver Detalhes de um Item Específico
### Expectativa: Retornar todos os dados do item usando o ID da URL
### ===================================================================
GET {{baseUrl}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}


### ===================================================================
### 8. [SUCESSO 200] Editar Informações de um Item (Apenas o Dono)
### Expectativa: Atualizar os dados enviados e retornar sucesso
### ===================================================================
PUT {{baseUrl}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "title": "Geladeira Brastemp (Semi-nova)",
  "description": "A geladeira já está limpa e pronta para retirada imediata!"
}


### ===================================================================
### 9. [SUCESSO 200] Alterar Status de um Item
### Expectativa: Mudar de 'Disponível' para 'Reservado' ou 'Doado'
### ===================================================================
PATCH {{baseUrl}}/items/{{itemId}}/status
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "status": "Reservado"
}

### ===================================================================
### 10. [SUCESSO 200] Apagar um Item (Soft Delete)
### Expectativa: Desativar a visualização do item (Apenas dono/Admin)
### ===================================================================
DELETE {{baseUrl}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}