### Criar um Item para Doação (Rota protegida)
POST http://localhost:3333/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWRkMGNlYy02MmMyLTRlNDgtOGU2OC1hOTFlN2E0MjM0OTkiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDgwNTAxfQ.kMN8uec6kZ4uXat2c2eSAeRtFfLK7diz5uuyH2tTogQ

{
  "title": "Sofá 3 Lugares Retrátil",
  "description": "Sofá em bom estado, cor cinza escuro. Precisa de frete grande para retirar.",
  "category": "Móveis",
  "imageUrls": ["https://exemplo.com/sofa.jpg"],
  "latitude": -23.501533,
  "longitude": -47.458112
}

### Criar um Item com 3 Imagens
POST http://localhost:3333/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWRkMGNlYy02MmMyLTRlNDgtOGU2OC1hOTFlN2E0MjM0OTkiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg4NTI3fQ.aDKvZO-tDAzPRG-37Z0UiI_xW7g2jCZMZdJ1o1dxZng

{
  "title": "Geladeira Brastemp",
  "description": "Geladeira funcionando perfeitamente, apenas com arranhões na porta.",
  "category": "Eletrodomésticos",
  "imageUrls": [
    "https://firebase.storage.com/minha-foto-1.jpg",
    "https://firebase.storage.com/minha-foto-2.jpg",
    "https://firebase.storage.com/minha-foto-3.jpg"
  ],
  "latitude": -23.501533,
  "longitude": -47.458112
}

### Listar itens (Sem filtros)
GET http://localhost:3333/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOGI4ZDY3Zi1iNWU5LTQwNzUtYWE5OC1kNjgwYWRkMzM3MzYiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg4ODYwfQ.HikJnsPuAo5JStSQH4fY9iNcKP1MD4McV-7FQqXbJI0
### Listar itens apenas da categoria "Móveis"
GET http://localhost:3333/items?category=Móveis
Authorization: Bearer EU_TOKEN_AQUI
### Listar itens perto de mim (Sorocaba)
GET http://localhost:3333/items?lat=-23.501533&lng=-47.458112
Authorization: Bearer EU_TOKEN_AQUI

### Ver detalhes de um item específico
GET http://localhost:3333/items/40d5de3f-0408-4dd0-a2e5-dd1fabf0bcf3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOGI4ZDY3Zi1iNWU5LTQwNzUtYWE5OC1kNjgwYWRkMzM3MzYiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg4ODYwfQ.HikJnsPuAo5JStSQH4fY9iNcKP1MD4McV-7FQqXbJI0

### Editar as informações de um item (Apenas o dono consegue)
PUT http://localhost:3333/items/40d5de3f-0408-4dd0-a2e5-dd1fabf0bcf3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWRkMGNlYy02MmMyLTRlNDgtOGU2OC1hOTFlN2E0MjM0OTkiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg5NTE0fQ.AcqxBWWadXSHg4_c5Fbq4U2NWN-YJFHQEzg5y5qA4Y8

{
  "title": "Geladeira Brastemp (Semi-nova)",
  "description": "A geladeira já está limpa e pronta para retirada imediata!"
}

### Alterar Status de um Item (Disponível -> Reservado)
PATCH http://localhost:3333/items/40d5de3f-0408-4dd0-a2e5-dd1fabf0bcf3/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWRkMGNlYy02MmMyLTRlNDgtOGU2OC1hOTFlN2E0MjM0OTkiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg5NTE0fQ.AcqxBWWadXSHg4_c5Fbq4U2NWN-YJFHQEzg5y5qA4Y8

{
  "status": "Reservado"
}

### Apagar um item (Soft Delete)
DELETE http://localhost:3333/items/fbde2312-d62d-4a18-9c7d-eef6772825a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWRkMGNlYy02MmMyLTRlNDgtOGU2OC1hOTFlN2E0MjM0OTkiLCJyb2xlIjoiRG9hZG9yIiwiaWF0IjoxNzc0NDg5NTE0fQ.AcqxBWWadXSHg4_c5Fbq4U2NWN-YJFHQEzg5y5qA4Y8
